### ISSUE TITLE
this.$router.back() don't refresh the this.$route.params from parent page.

### ISSUE THREAD

**Issue by JCKodel** [framework7io/framework7-vue#253] opened 2017-10-03 02:00 UTC
Page 1: /feed/:_id (this.$route.params._id works fine).
Then, this.$router.load({url:"/login/"}) to navigate to a login page.
When user has logged in, a this.$router.back() is executed.
After the 1st page is mounted, this.$route.params._id is undefined and this.$route.url = "/login/"

It seems that $router.back() don't refresh the current $route.[...]

**Comment by lxmfly123** [comment] 2017-10-10 02:46
Just encountered the same issue.

**Comment by AGhasemzadeh** [comment] 2017-10-19 16:01
I have this problem too.

**Comment by Andorxor** [comment] 2017-10-26 10:19
I have this issue too. The issue is also in kitchen-sink. If you go for instance to "/accordion/" you have $route.params.path="/accordion/", if you than go back, $route.params.path stays unchanged, i.e. "/accordion/". Is it supposed to be this way?

**Comment by AGhasemzadeh** [comment] 2017-10-27 01:11
Solution:
Save params to other variable.
for example:
`<script>
  export default {
    props: ['city'],
    data: function() {
        return {
            cityName:null,
            weburl:process.env.MIX_APP_URL,
            pools: null,
        }
    },
    mounted: function() {
        var v = this;
        v.cityName = this.$route.params.city;
        axios.get(process.env.MIX_APP_URL + '/api/city/'+this.$route.params.city)
          .then(function (response) {
            
            v.pools = response.data.pools;
          })
          .catch(function (error) {
            console.log(error);
          });
          

    }
  }
</script>`

**Comment by JCKodel** [comment] 2017-10-27 13:35
This is a work-around, not a "solution"

Em 26 de out de 2017 23:11, "Ali Ghasemzadeh" <notifications@github.com>
escreveu:

**Comment by nolimits4web** [comment] 2018-01-30 14:43
Closing as looks like not the case in v2

**Closed by nolimits4web** 2018-01-30 14:43 UTC

**Comment by JasonLandbridge** [comment] 2018-08-24 21:19
This is still a problem in v3. What was done to fix this?

This works:
`this.$f7router.navigate('/rent-calculator/1');`

This doesn't:
`this.$f7router.back('/rent-calculator/1');`

**Comment by kenziD** [comment] 2018-08-27 15:32
same issue here

**Comment by tomc1998** [comment] 2019-10-01 15:33
Any updates here...?
