### ISSUE TITLE
How to use Vue data on framework7 initialization

### ISSUE THREAD

**Issue by scriptPilot** [framework7io/framework7-vue#144] opened 2017-04-25 16:30 UTC
Hey Vladimir, is there a way to use Vue component data on Framework7 initialization?

Example:

```
...
data: {
  root: '#app'
  ...
},
framework7: {
  root: this.root,
  ...
}
...
```

**Comment by scriptPilot** [comment] 2017-04-26 19:55
I figured out, until `beforeMount()` it's possible to assign values like this:

```
beforeMount: function () {
  this.$options.framework7.root = '#app'
}
```

**Comment by scriptPilot** [comment] 2017-04-26 21:27
Mhm, so I can change all data like shown above, but not the theme.
In the code I see that I could pass it by the plugin params:

`vue.use(require('../vendor/framework7-vue/framework7-vue.js'), {theme: 'material'})``

But why is it not possible to change the theme later on?
With the following try I will have some kind of a mix ...

```
beforeMount: function () {
  this.$options.framework7.theme = 'material'
}
```

**Comment by nolimits4web** [comment] 2017-04-28 13:14
F7 got init in `mounted` hook, so you do it right, you can change it in hooks that fires before `mounted`

**Comment by BHunter2889** [comment] 2017-04-28 15:23
In regards to the above commit, is this released? And should we be grabbing the new version? I'm new and just now starting to get into the data binding portion so I'm just curious.

**Comment by scriptPilot** [comment] 2017-04-28 15:25
@nolimits4web - I thought so, but Material will be init correctly only if I pass the argument on framework7: {} or as use... component param.

The approach with beforeMount does not work.

Or does it work for you well?

**Comment by scriptPilot** [comment] 2017-04-28 19:14
@nolimits4web

I use the following code:

```
...
created: function () {
  this.$options.framework7.material = true
}
...
```

The result is a mix of iOS and Material style:

![bildschirmfoto 2017-04-28 um 21 10 34](https://cloud.githubusercontent.com/assets/19615586/25543539/355c1b82-2c57-11e7-9973-0618a1153467.png)
![bildschirmfoto 2017-04-28 um 21 10 41](https://cloud.githubusercontent.com/assets/19615586/25543540/355d8d46-2c57-11e7-8e7e-80c95d2a97fe.png)

If I add `vue.use(require('../framework7-vue.js'), {theme: 'material'})` the outcome is correct:

![bildschirmfoto 2017-04-28 um 21 12 47](https://cloud.githubusercontent.com/assets/19615586/25543594/791241d0-2c57-11e7-8d0c-ea6b0a208572.png)
![bildschirmfoto 2017-04-28 um 21 12 54](https://cloud.githubusercontent.com/assets/19615586/25543595/793ecdb8-2c57-11e7-9575-464d88dff3c3.png)

That's strange, isn't it?

Dennis

**Comment by scriptPilot** [comment] 2017-04-30 14:10
@nolimits4web - Ist it by design or not wanted?

**Comment by BHunter2889** [comment] 2017-05-01 22:49
So, now that I've actually gotten into the data, I'm seeing an interesting pattern with my issue and I think it can be resolved by creating an event and callback handler (or if anyone knows how to make `mounted` wait, please let me know, I'm fairly new to Vue). My issue is that in `created:` I initialize my connection to my deepstream.io server (websocket data streaming server), but that doesn't finish executing until _after_ `mounted:` is already in progress. The data in `mounted:`, where I specify DOM elements and framework7 in initialized, _depends_ on the data that has not yet been grabbed from the deepstream.io connection since it has not yet finished opening the connection. It might be enough to use `beforeMount:` though I'm not sure if `mounted:` waits for `beforeMount:` to finish executing? I figured it would for `created:` but I was apparently wrong about that...

**Comment by nolimits4web** [comment] 2018-01-30 15:00
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7 & Framework7-Vue, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue

**Closed by nolimits4web** 2018-01-30 15:00 UTC
